# api config
server:
  port: 8152
  shutdown: graceful
swagger:
  enabled: true
spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s

# model config
model:
  name: llama2
  path: /llama.cpp/models/llama2/ggml-model-7b-q6_k.gguf
